syntax = "proto3";

package entity;

option csharp_namespace = "App.Protobuf.Entity";

enum GemHistoryReason {
	GEM_HISTORY_REASON_UNSPECIFIED = 0;
	GEM_HISTORY_REASON_PRESENT_TYPE = 1;
	GEM_HISTORY_REASON_SHOP_PURCHASE = 2;
	GEM_HISTORY_REASON_MONTHLY_PASS = 3;
	GEM_HISTORY_REASON_EVENT_BOX_GACHA = 4;
	GEM_HISTORY_REASON_STORY = 5;
	GEM_HISTORY_REASON_INITIAL_DATA = 6;
	GEM_HISTORY_REASON_ADMIN = 7;
	GEM_HISTORY_REASON_DEBUG = 8;
	GEM_HISTORY_REASON_FRIENDSHIP_STORY = 9;
	GEM_HISTORY_REASON_SHOP = 11;
	GEM_HISTORY_REASON_GACHA = 12;
	GEM_HISTORY_REASON_LIVE_BOOST = 13;
	GEM_HISTORY_REASON_VIP_RANK_PACK = 14;
	GEM_HISTORY_REASON_SEASON_PASS = 15;
	GEM_HISTORY_REASON_CIRCLE_CREATE = 16;
}

message Gem {
	int32 free = 1;
	int32 paid = 2;
	int32 platform_android = 3;
	int32 platform_ios = 4;
	int32 platform_ex = 5;
}

message GemHistory {
	int64 changed_at = 1;
	int32 free_amount = 2;
	int32 paid_amount = 3;
	GemHistoryReason reason = 4;
	int64 reason_id = 5;
	bool via_present_box = 6;
}
