syntax = "proto3";

package entity;

option csharp_namespace = "App.Protobuf.Entity";

message Maintenance {
	string id = 1;
	int64 start_at = 2;
	int64 end_at = 3;
	bool is_total = 4;
	MaintenanceFeatures features = 5;
	MaintenancePlatforms platforms = 6;
	string free_text = 7;
	bool is_emergency = 8;
}

message MaintenanceFeatures {
	bool shop = 1;
	bool gacha = 2;
	bool story = 3;
	bool rank_match = 4;
	bool casual_match = 5;
	bool circle = 6;
}

message MaintenancePlatforms {
	bool ios = 1;
	bool android = 2;
	bool others = 3;
}
