syntax = "proto3";

import "entity/band_item.proto";
import "entity/carousel_help.proto";
import "entity/character.proto";
import "entity/character_costume.proto";
import "entity/comeback.proto";
import "entity/content_unlock.proto";
import "entity/deck.proto";
import "entity/degree.proto";
import "entity/event.proto";
import "entity/exchange.proto";
import "entity/gacha.proto";
import "entity/gem.proto";
import "entity/item.proto";
import "entity/live.proto";
import "entity/liveboost.proto";
import "entity/livemusic.proto";
import "entity/login_bonus.proto";
import "entity/member_card.proto";
import "entity/memory.proto";
import "entity/mission.proto";
import "entity/monthly_pass.proto";
import "entity/personal_notification.proto";
import "entity/player_profile.proto";
import "entity/profilecard.proto";
import "entity/shop.proto";
import "entity/spot.proto";
import "entity/stamp.proto";
import "entity/story_episode.proto";
import "entity/support_card.proto";
import "entity/tutorial.proto";
import "entity/vip.proto";

package entity;

option csharp_namespace = "App.Protobuf.Entity";

enum LinkedAccountType {
	LINKED_ACCOUNT_TYPE_UNSPECIFIED = 0;
	LINKED_ACCOUNT_TYPE_APPLE = 1;
	LINKED_ACCOUNT_TYPE_GOOGLE = 2;
	LINKED_ACCOUNT_TYPE_GAME_CENTER = 3;
	LINKED_ACCOUNT_TYPE_BUSHIROAD = 4;
}

message PlayerCredential {
	string id = 1;
	string credential = 2;
	string device_id = 3;
	int64 profile_id = 4;
}

message PlayerData {
	repeated Item items = 1;
	repeated MemberCard member_cards = 2;
	repeated SupportCard support_cards = 3;
	repeated Deck decks = 4;
	int32 main_deck = 5;
	Gem gem = 6;
	LiveBoost live_boost = 7;
	repeated BandItem band_items = 8;
	int32 player_rank_exp = 9 [deprecated = true];
	repeated LiveScore live_score = 10;
	repeated LiveMusicReward live_music_reward = 11;
	repeated CharacterRank character_rank = 12;
	repeated CharacterFriendship character_friendship = 13;
	repeated CharacterRankReward character_rank_reward = 14 [deprecated = true];
	repeated CharacterFriendshipRankReward character_friendship_rank_reward = 15;
	repeated StoryEpisode seen_story_episodes = 16;
	repeated StoryEpisode seen_story_friendship_episodes = 17;
	LiveSkip live_skip = 18;
	repeated GachaCount gacha_count = 19;
	repeated LiveMusic live_music = 20;
	repeated ExchangeCount exchange_count = 21;
	repeated GachaPoint gacha_point = 22;
	repeated LoginBonusSheet login_bonus_update = 23;
	PlayerMissionData player_mission_data = 24;
	repeated Event events = 25;
	repeated EventBoxGachaReward event_box_gacha_rewards = 26;
	repeated Stamp stamps = 27;
	LiveSetting live_setting = 28;
	repeated LiveLaneSkin live_lane_skins = 29;
	repeated LiveNoteSkin live_note_skins = 30;
	repeated LiveNoteEffectSkin live_note_effect_skins = 31;
	repeated LiveNoteSeGroup live_note_se_groups = 32;
	repeated CarouselHelp shown_carousel_helps = 33;
	PlayerSimpleProfile my_profile = 34;
	LiveStampReward live_stamp_reward = 35;
	repeated LiveMusicComboReward live_music_combo_reward = 36;
	Comeback comeback = 37;
	repeated StampFavoriteName stamp_favorite_names = 38;
	repeated ContentUnlock shown_content_unlocks = 39;
	optional uint64 circle_id = 40;
	repeated ChallengeLive challenge_live = 41;
	repeated PurchaseTransaction remain_transactions = 42;
	repeated Degree degrees = 43;
	repeated int64 chat_themes = 44;
	repeated int64 chat_bubbles = 45;
	repeated int64 chat_frames = 46;
	bool has_password = 47;
	repeated LinkedAccountType linked_account_types = 48;
	MemoryStatus memory_status = 49;
	Vip vip = 50;
	repeated ProfileCardDetail profile_card_details = 51;
	repeated MonthlyPassState monthly_passes = 52;
	TutorialProgress tutorial_progress = 53;
	repeated int64 background_ids = 54;
	repeated int64 character_orders = 55;
	repeated int64 favorite_spot_ids = 56;
	repeated Spot spots = 57;
	bool is_night_notice_off = 58;
	repeated MusicPuzzle puzzles = 59;
	PersonalNotification personal_notification = 60;
	repeated CharacterCurrentCostume character_current_costumes = 61;
	repeated CharacterUnlockedCostume character_unlocked_costumes = 62;
}
