syntax = "proto3";

import "entity/resource.proto";

package entity;

option csharp_namespace = "App.Protobuf.Entity";

enum UnreceiveReason {
	UNRECEIVE_REASON_UNSPECIFIED = 0;
	UNRECEIVE_REASON_LIMIT_REACHED = 1;
	UNRECEIVE_REASON_EXPIRED = 2;
}

message PresentResource {
	ResourceType resource_type = 1;
	int64 resource_id = 2;
	int32 resource_count = 3;
}

message Present {
	uint64 present_id = 1;
	int64 post_at = 2;
	optional int64 expire_at = 3;
	PresentResource present_resource = 4;
	PresentTitle title = 5;
}

message PresentTitle {
	int64 present_type_id = 1;
	string present_param_1 = 2;
	string present_param_2 = 3;
}

message PresentUnreceived {
	uint64 present_id = 1;
	UnreceiveReason reason = 2;
}

message PresentHistory {
	uint64 present_id = 1;
	int64 post_at = 2;
	int64 got_at = 3;
	PresentResource present_resource = 4;
	PresentTitle title = 5;
	PresentResource converted_resource = 6;
}
