syntax = "proto3";

package entity;

option csharp_namespace = "App.Protobuf.Entity";

enum ResourceType {
	RESOURCE_TYPE_UNSPECIFIED = 0;
	RESOURCE_TYPE_ITEM = 1;
	RESOURCE_TYPE_MEMBER_CARD = 2;
	RESOURCE_TYPE_SUPPORT_CARD = 3;
	RESOURCE_TYPE_VOICE = 4;
	RESOURCE_TYPE_LOGIN_BONUS = 5;
	RESOURCE_TYPE_SUBSCRIPTION = 6;
	RESOURCE_TYPE_GACHA_POINT = 7;
	RESOURCE_TYPE_MUSIC = 8;
	RESOURCE_TYPE_STAMP = 9;
	RESOURCE_TYPE_PREMIUM_PASS = 10;
	RESOURCE_TYPE_EVENT_MEDAL = 11;
	RESOURCE_TYPE_LANE_SKIN = 12;
	RESOURCE_TYPE_NOTE_SKIN = 13;
	RESOURCE_TYPE_NOTE_EFFECT_SKIN = 14;
	RESOURCE_TYPE_NOTE_SE_GROUP = 15;
	RESOURCE_TYPE_VIP_POINT = 16;
	RESOURCE_TYPE_DEGREE = 17;
	RESOURCE_TYPE_BACKGROUND = 18;
	RESOURCE_TYPE_SPOT = 19;
	RESOURCE_TYPE_CHARACTER_UNLOCKED_COSTUME = 20;
}
