syntax = "proto3";

import "entity/liveboost.proto";
import "entity/notification.proto";
import "google/protobuf/empty.proto";

package app.liveboost;

option csharp_namespace = "App.Protobuf.LiveBoost";

message LiveBoostRecoveryRequest {
	int32 type = 1;
	int32 star_amount = 2;
	map<int64, int32> items = 3;
}

message LiveBoostRecoveryResponse {
	.entity.LiveBoost live_boost = 1;
	.entity.Notification notification = 2;
}

message LiveBoostReqCheckResponse {
	uint32 time_limit = 1;
}

message LiveBoostHelpRequest {
	uint64 request_id = 1;
}

service LiveBoostService {
	rpc Recovery (.app.liveboost.LiveBoostRecoveryRequest) returns (.app.liveboost.LiveBoostRecoveryResponse);
	rpc LiveBoostReqCheck (.google.protobuf.Empty) returns (.app.liveboost.LiveBoostReqCheckResponse);
	rpc LiveBoostReq (.google.protobuf.Empty) returns (.google.protobuf.Empty);
	rpc LiveBoostHelp (.app.liveboost.LiveBoostHelpRequest) returns (.google.protobuf.Empty);
}
