syntax = "proto3";

import "entity/notification.proto";

package app.pieceexchange;

option csharp_namespace = "App.Protobuf.PieceExchange";

message PieceExchangeRequest {
	repeated Piece pieces = 1;
	repeated DuplicateSupportCard support_cards = 2;
}

message PieceExchangeResponse {
	.entity.Notification notification = 1;
}

message Piece {
	int64 id = 1;
	int32 count = 2;
}

message DuplicateSupportCard {
	int64 support_card_master_id = 1;
	int32 count = 2;
}

service PieceExchangeService {
	rpc Exchange (.app.pieceexchange.PieceExchangeRequest) returns (.app.pieceexchange.PieceExchangeResponse);
}
