syntax = "proto3";

import "entity/mission.proto";
import "entity/notification.proto";
import "entity/season_pass.proto";

package app.seasonpass;

option csharp_namespace = "App.Protobuf.SeasonPass";

message FetchSeasonPassRequest {
}

message FetchSeasonPassResponse {
	repeated .entity.MissionCounter mission_counters = 1;
	repeated .entity.SeasonPassDetail season_passes = 2;
}

message ReceiveMissionRequest {
	int64 season_pass_id = 1;
	repeated int64 season_pass_mission_ids = 2;
}

message ReceiveMissionResponse {
}

message ReceiveRewardRequest {
	int64 season_pass_id = 1;
}

message ReceiveRewardResponse {
	.entity.Notification notification = 1;
}

message PurchaseRequest {
	int64 season_pass_id = 1;
	int32 before_point = 2;
	int32 after_point = 3;
}

message PurchaseResponse {
	.entity.Notification notification = 1;
}

service SeasonPassService {
	rpc Fetch (.app.seasonpass.FetchSeasonPassRequest) returns (.app.seasonpass.FetchSeasonPassResponse);
	rpc ReceiveMission (.app.seasonpass.ReceiveMissionRequest) returns (.app.seasonpass.ReceiveMissionResponse);
	rpc ReceiveReward (.app.seasonpass.ReceiveRewardRequest) returns (.app.seasonpass.ReceiveRewardResponse);
	rpc Purchase (.app.seasonpass.PurchaseRequest) returns (.app.seasonpass.PurchaseResponse);
}
