syntax = "proto3";

import "entity/notification.proto";
import "entity/offline_bonus.proto";

package app.offlinebonus;

option csharp_namespace = "App.Protobuf.OfflineBonus";

message StatusRequest {
}

message StatusResponse {
	.entity.OfflineBonus offline_bonus = 1;
	repeated .entity.OfflineBonusUnitLite offline_bonus_units = 2;
}

message DetailRequest {
	int64 offline_bonus_unit_id = 1;
}

message DetailResponse {
	.entity.OfflineBonusUnit offline_bonus_unit = 1;
}

message ReceiveRequest {
	repeated int64 offline_bonus_unit_ids = 1;
}

message ReceiveResponse {
	repeated .entity.OfflineBonusUnitResult unit_results = 1;
	.entity.Notification notification = 2;
}

message SkipRequest {
	int64 offline_bonus_unit_id = 1;
	int32 type = 2;
	int64 item_master_id = 3;
}

message SkipResponse {
	.entity.OfflineBonus offline_bonus = 1;
	.entity.OfflineBonusUnitResult unit_result = 2;
	.entity.Notification notification = 3;
}

message ReceiveStockRequest {
	int64 offline_bonus_unit_id = 1;
}

message ReceiveStockResponse {
	.entity.OfflineBonusUnitResult unit_result = 1;
	.entity.Notification notification = 2;
}

service OfflineBonusService {
	rpc Status (.app.offlinebonus.StatusRequest) returns (.app.offlinebonus.StatusResponse);
	rpc Detail (.app.offlinebonus.DetailRequest) returns (.app.offlinebonus.DetailResponse);
	rpc Receive (.app.offlinebonus.ReceiveRequest) returns (.app.offlinebonus.ReceiveResponse);
	rpc Skip (.app.offlinebonus.SkipRequest) returns (.app.offlinebonus.SkipResponse);
	rpc ReceiveStock (.app.offlinebonus.ReceiveStockRequest) returns (.app.offlinebonus.ReceiveStockResponse);
}
