syntax = "proto3";

import "entity/deck.proto";
import "entity/notification.proto";
import "entity/player_profile.proto";

package app.event;

option csharp_namespace = "App.Protobuf.Event";

message ExecuteBoxGachaRequest {
	int64 event_id = 1;
	int32 count = 2;
}

message ExecuteBoxGachaResponse {
	repeated int64 reward_id = 1;
	.entity.Notification notification = 2;
}

message ResetBoxGachaRequest {
	int64 event_id = 1;
}

message ResetBoxGachaResponse {
}

message GetRankRequest {
	int64 event_id = 1;
}

message GetRankResponse {
	int32 rank = 1;
}

message GetDeckRequest {
	string player_id = 1;
	int64 event_id = 2;
}

message GetDeckResponse {
	.entity.DeckDetail deck = 1;
}

message GetRankingListRequest {
	int64 event_id = 1;
	repeated int32 ranks = 2;
}

message EventRankingEntry {
	.entity.PlayerSimpleProfile profile = 1;
	int32 rank = 2;
	int32 point = 3;
}

message GetRankingListResponse {
	repeated EventRankingEntry ranking = 1;
}

message GetChallengeMusicRankingRequest {
	int64 challenge_music_id = 1;
}

message ChallengeLiveRankingPlayer {
	.entity.PlayerSimpleProfile player_data = 1;
	int32 score = 3;
	.entity.DeckDetail high_score_deck = 4;
}

message GetChallengeMusicRankingResponse {
	repeated ChallengeLiveRankingPlayer players = 1;
	int32 my_rank = 2;
	int32 my_score = 3;
}

service EventService {
	rpc ExecuteBoxGacha (.app.event.ExecuteBoxGachaRequest) returns (.app.event.ExecuteBoxGachaResponse);
	rpc ResetBoxGacha (.app.event.ResetBoxGachaRequest) returns (.app.event.ResetBoxGachaResponse);
	rpc GetRank (.app.event.GetRankRequest) returns (.app.event.GetRankResponse);
	rpc GetDeck (.app.event.GetDeckRequest) returns (.app.event.GetDeckResponse);
	rpc GetRankingList (.app.event.GetRankingListRequest) returns (.app.event.GetRankingListResponse);
	rpc GetChallengeMusicRanking (.app.event.GetChallengeMusicRankingRequest) returns (.app.event.GetChallengeMusicRankingResponse);
}
