syntax = "proto3";

import "entity/announcement.proto";
import "entity/method_options/method_options.proto";

package app.announcement;

option csharp_namespace = "App.Protobuf.Announcement";

enum Tab {
	ALL = 0;
	OPENING_EVENTS = 1;
	BUG = 2;
}

message GetListRequest {
	Tab selected_tab = 1;
}

message GetListResponse {
	repeated .entity.Announcement announcements = 1;
	repeated .entity.AnnouncementExternalContent external_contents = 2;
}

message GetRequest {
	int64 id = 1;
}

message GetResponse {
	.entity.Announcement announcement = 1;
}

service AnnouncementService {
	rpc GetList (.app.announcement.GetListRequest) returns (.app.announcement.GetListResponse) {
		option (entity.method_options.skip_authentication) = true;
	}

	rpc Get (.app.announcement.GetRequest) returns (.app.announcement.GetResponse) {
		option (entity.method_options.skip_authentication) = true;
	}
}
