syntax = "proto3";

import "entity/method_options/method_options.proto";
import "entity/notification.proto";

package app.story;

option csharp_namespace = "App.Protobuf.Story";

message ReadStoryEpisodeRequest {
	int64 episode_id = 1;
	bool is_skipped = 2;
}

message ReadStoryEpisodeResponse {
	bool is_valid_band_rank = 1;
	.entity.Notification notification = 2;
}

message ReadFriendshipEpisodeRequest {
	int64 episode_id = 1;
	bool is_skipped = 2;
}

message ReadFriendshipEpisodeResponse {
	.entity.Notification notification = 1;
}

message CheckMaintenanceStoryRequest {
}

message CheckMaintenanceStoryResponse {
}

service StoryService {
	rpc ReadStoryEpisode (.app.story.ReadStoryEpisodeRequest) returns (.app.story.ReadStoryEpisodeResponse) {
		option (entity.method_options.maintenance_features).story = true;
	}

	rpc ReadFriendshipEpisode (.app.story.ReadFriendshipEpisodeRequest) returns (.app.story.ReadFriendshipEpisodeResponse) {
		option (entity.method_options.maintenance_features).story = true;
	}

	rpc CheckMaintenanceStory (.app.story.CheckMaintenanceStoryRequest) returns (.app.story.CheckMaintenanceStoryResponse) {
		option (entity.method_options.maintenance_features).story = true;
	}
}
